services:
  - type: web
    name: fastapi-app
    runtime: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://aichatbot-six-tau.vercel.app,http://localhost:3000"
